# Task 1: Comparisson of sentences

At first, we need to import data from file `sentences.txt` and parse it (don't forget to delete all empty strings)

In [1]:
import re
import numpy as np

In [2]:
ifile = open('sentences.txt')
data = []
n = 0;
for line in ifile:
    data.append(list((val for val in re.split('[^a-z]', line.lower()) if val != '')))
    n += 1;
ifile.close()

Then, we assign a number from 0 to (d-1) to each word in the sentences (_d_ - _number_ _of_ _all_ _words_ ). For that we use type `dict`:

In [3]:
d = 0
data_dic = {}

for line in data:
    for elem in line:
        if data_dic.get(elem) == None:
            data_dic[elem] = d;
            d += 1

Now we need to create new array with _n_ rows and _d_ columns. Number at _(i,j)_ position equals to number of j-th word in i-th sentense.

In [4]:
print (n, d)

22 254


In [5]:
data_word_counts = np.zeros((n,d))

for i in range(n):
    for elem in data[i]:
        data_word_counts[i][data_dic.get(elem)] += 1;
        
print(data_word_counts)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


And now we will find distances between first and each other sentences using `scipy.spatial.distance.cosine`:

In [6]:
from scipy.spatial.distance import cosine

In [7]:
for i in range (1,n):
    print(i,') ', cosine(data_word_counts[0], data_word_counts[i]), sep = '')

1) 0.9527544408738466
2) 0.8644738145642124
3) 0.8951715163278082
4) 0.7770887149698589
5) 0.9402385695332803
6) 0.7327387580875756
7) 0.9258750683338899
8) 0.8842724875284311
9) 0.9055088817476932
10) 0.8328165362273942
11) 0.8804771390665607
12) 0.8396432548525454
13) 0.8703592552895671
14) 0.8740118423302576
15) 0.9442721787424647
16) 0.8406361854220809
17) 0.956644501523794
18) 0.9442721787424647
19) 0.8885443574849294
20) 0.8427572744917122
21) 0.8250364469440588


As we see, the closest sentences to the first are 6th and 4th. Let's put the answer in the file `'submission-1.txt'`

In [8]:
ofile = open('submission-1.txt','w')
ofile.write('6 4')
ofile.close()